[global]
keyboard = "en-us"
country = "fr"
fqdn = "nbTestInstall.pve"
mailto = "mail@no.com"
timezone = "Europe/Brussels"
root_password = "12345678"

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "zfs"
disk_list = ['sda', 'sdb']
zfs.raid = "raid1"